package cli

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/tiaanduplessis/envy/internal/config"
	"github.com/tiaanduplessis/envy/internal/dotenv"
)

func NewLoadCmd(store *config.Store) *cobra.Command {
	return newLoadCmd(store, nil)
}

func newLoadCmd(store *config.Store, stdin io.Reader) *cobra.Command {
	var project string
	var env string
	var path string
	var output string
	var format string
	var force bool
	var dryRun bool
	var allPaths bool

	cmd := &cobra.Command{
		Use:   "load",
		Short: "Write a .env file from stored config",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if allPaths && path != "" {
				return fmt.Errorf("--all-paths and --path are mutually exclusive")
			}
			if allPaths && cmd.Flags().Changed("output") {
				return fmt.Errorf("--all-paths and --output are mutually exclusive")
			}

			p, err := store.Load(project)
			if err != nil {
				return err
			}

			targetEnv := config.ResolveEnv(env, p.DefaultEnv)

			var f dotenv.Format
			switch format {
			case "export":
				f = dotenv.FormatExport
			default:
				f = dotenv.FormatDotenv
			}

			if allPaths {
				return loadAllPaths(cmd, p, targetEnv, f, force, dryRun, stdin)
			}

			outputFile := config.ResolveOutputFile(p, targetEnv, output, cmd.Flags().Changed("output"))

			vars, err := config.ResolveVars(p, targetEnv, path)
			if err != nil {
				return err
			}

			header := fmt.Sprintf("Generated by envy — project: %s, env: %s", p.Name, targetEnv)
			if path != "" {
				header += fmt.Sprintf(", path: %s", path)
			}

			opts := dotenv.WriteOptions{
				Format: f,
				Header: header,
				Sorted: true,
			}

			if dryRun {
				return dotenv.Write(cmd.OutOrStdout(), vars, opts)
			}

			if !force {
				if _, err := os.Stat(outputFile); err == nil {
					reader := stdin
					if reader == nil {
						reader = os.Stdin
					}
					fmt.Fprintf(cmd.OutOrStdout(), "File %q already exists. Overwrite? [y/N] ", outputFile)
					scanner := bufio.NewScanner(reader)
					scanner.Scan()
					answer := scanner.Text()
					if answer != "y" && answer != "Y" {
						fmt.Fprintln(cmd.OutOrStdout(), "Aborted.")
						return nil
					}
				}
			}

			file, err := os.Create(outputFile)
			if err != nil {
				return fmt.Errorf("creating %q: %w", outputFile, err)
			}
			defer file.Close()

			if err := dotenv.Write(file, vars, opts); err != nil {
				return err
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Wrote %d variable(s) to %s\n", len(vars), outputFile)
			return nil
		},
	}

	cmd.Flags().StringVar(&project, "project", "", "project name (required)")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&env, "env", "", "environment")
	cmd.Flags().StringVar(&path, "path", "", "monorepo subpath")
	cmd.Flags().StringVar(&output, "output", ".env", "output filename")
	cmd.Flags().StringVar(&format, "format", "dotenv", "output format (dotenv|export)")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite without confirmation")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "print to stdout instead of writing file")
	cmd.Flags().BoolVar(&allPaths, "all-paths", false, "write .env files for all configured paths")

	return cmd
}

type writeTarget struct {
	path       string
	outputPath string
	vars       map[string]string
	header     string
}

func loadAllPaths(
	cmd *cobra.Command,
	p *config.Project,
	targetEnv string,
	format dotenv.Format,
	force, dryRun bool,
	stdin io.Reader,
) error {
	type envEntry struct {
		env      string
		filename string
	}

	seenFiles := make(map[string]bool)
	var envs []envEntry

	resolvedFile := config.ResolveOutputFile(p, targetEnv, "", false)
	envs = append(envs, envEntry{targetEnv, resolvedFile})
	seenFiles[resolvedFile] = true

	for _, env := range sortedKeys(p.EnvFiles) {
		if env == targetEnv {
			continue
		}
		filename := p.EnvFiles[env]
		if seenFiles[filename] {
			continue
		}
		envs = append(envs, envEntry{env, filename})
		seenFiles[filename] = true
	}

	var targets []writeTarget

	for _, e := range envs {
		rootVars, err := config.ResolveVars(p, e.env, "")
		if err != nil {
			continue
		}
		if len(rootVars) == 0 {
			continue
		}
		targets = append(targets, writeTarget{
			outputPath: e.filename,
			vars:       rootVars,
			header:     fmt.Sprintf("Generated by envy — project: %s, env: %s", p.Name, e.env),
		})
	}

	for _, pth := range sortedKeys(p.Paths) {
		for _, e := range envs {
			if e.env != targetEnv {
				if p.Paths[pth] == nil || p.Paths[pth][e.env] == nil {
					continue
				}
			}
			pathVars, err := config.ResolveVars(p, e.env, pth)
			if err != nil {
				continue
			}
			targets = append(targets, writeTarget{
				path:       pth,
				outputPath: filepath.Join(pth, e.filename),
				vars:       pathVars,
				header:     fmt.Sprintf("Generated by envy — project: %s, env: %s, path: %s", p.Name, e.env, pth),
			})
		}
	}

	if dryRun {
		for i, t := range targets {
			if i > 0 {
				fmt.Fprintln(cmd.OutOrStdout())
			}
			fmt.Fprintf(cmd.OutOrStdout(), "=== %s ===\n", t.outputPath)
			opts := dotenv.WriteOptions{
				Format: format,
				Header: t.header,
				Sorted: true,
			}
			if err := dotenv.Write(cmd.OutOrStdout(), t.vars, opts); err != nil {
				return err
			}
		}
		return nil
	}

	if !force {
		reader := stdin
		if reader == nil {
			reader = os.Stdin
		}
		fmt.Fprintf(cmd.OutOrStdout(), "Write %d .env file(s):\n", len(targets))
		for _, t := range targets {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s\n", t.outputPath)
		}
		fmt.Fprint(cmd.OutOrStdout(), "Proceed? [y/N] ")
		scanner := bufio.NewScanner(reader)
		scanner.Scan()
		if answer := scanner.Text(); answer != "y" && answer != "Y" {
			fmt.Fprintln(cmd.OutOrStdout(), "Aborted.")
			return nil
		}
	}

	var errors []string
	for _, t := range targets {
		if t.path != "" {
			if err := os.MkdirAll(filepath.Dir(t.outputPath), 0o755); err != nil {
				errors = append(errors, fmt.Sprintf("%s: %v", t.outputPath, err))
				continue
			}
		}

		opts := dotenv.WriteOptions{
			Format: format,
			Header: t.header,
			Sorted: true,
		}

		file, err := os.Create(t.outputPath)
		if err != nil {
			errors = append(errors, fmt.Sprintf("%s: %v", t.outputPath, err))
			continue
		}

		if err := dotenv.Write(file, t.vars, opts); err != nil {
			file.Close()
			errors = append(errors, fmt.Sprintf("%s: %v", t.outputPath, err))
			continue
		}
		file.Close()

		fmt.Fprintf(cmd.OutOrStdout(), "Wrote %d variable(s) to %s\n", len(t.vars), t.outputPath)
	}

	if len(errors) > 0 {
		for _, e := range errors {
			fmt.Fprintf(cmd.ErrOrStderr(), "Error: %s\n", e)
		}
		return fmt.Errorf("failed to write %d file(s)", len(errors))
	}

	return nil
}
