package cli

import (
	"bufio"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"github.com/tiaanduplessis/envy/internal/config"
	"github.com/tiaanduplessis/envy/internal/dotenv"
)

func NewLoadCmd(store *config.Store) *cobra.Command {
	return newLoadCmd(store, nil)
}

func newLoadCmd(store *config.Store, stdin io.Reader) *cobra.Command {
	var project string
	var env string
	var path string
	var output string
	var format string
	var force bool
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "load",
		Short: "Write a .env file from stored config",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			p, err := store.Load(project)
			if err != nil {
				return err
			}

			targetEnv := config.ResolveEnv(env, p.DefaultEnv)
			vars, err := config.ResolveVars(p, targetEnv, path)
			if err != nil {
				return err
			}

			var f dotenv.Format
			switch format {
			case "export":
				f = dotenv.FormatExport
			default:
				f = dotenv.FormatDotenv
			}

			header := fmt.Sprintf("Generated by envy — project: %s, env: %s", p.Name, targetEnv)
			if path != "" {
				header += fmt.Sprintf(", path: %s", path)
			}

			opts := dotenv.WriteOptions{
				Format: f,
				Header: header,
				Sorted: true,
			}

			if dryRun {
				return dotenv.Write(cmd.OutOrStdout(), vars, opts)
			}

			if !force {
				if _, err := os.Stat(output); err == nil {
					reader := stdin
					if reader == nil {
						reader = os.Stdin
					}
					fmt.Fprintf(cmd.OutOrStdout(), "File %q already exists. Overwrite? [y/N] ", output)
					scanner := bufio.NewScanner(reader)
					scanner.Scan()
					answer := scanner.Text()
					if answer != "y" && answer != "Y" {
						fmt.Fprintln(cmd.OutOrStdout(), "Aborted.")
						return nil
					}
				}
			}

			file, err := os.Create(output)
			if err != nil {
				return fmt.Errorf("creating %q: %w", output, err)
			}
			defer file.Close()

			if err := dotenv.Write(file, vars, opts); err != nil {
				return err
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Wrote %d variable(s) to %s\n", len(vars), output)
			return nil
		},
	}

	cmd.Flags().StringVar(&project, "project", "", "project name (required)")
	cmd.MarkFlagRequired("project")
	cmd.Flags().StringVar(&env, "env", "", "environment")
	cmd.Flags().StringVar(&path, "path", "", "monorepo subpath")
	cmd.Flags().StringVar(&output, "output", ".env", "output filename")
	cmd.Flags().StringVar(&format, "format", "dotenv", "output format (dotenv|export)")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite without confirmation")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "print to stdout instead of writing file")

	return cmd
}
