package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tiaanduplessis/envy/internal/config"
)

func TestLoadCmd_DryRun(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("foo", []string{"dev"}, "dev")
	p.SetVar("dev", "DB", "localhost")
	p.SetVar("dev", "PORT", "5432")
	store.Save(p)

	root := NewRootCmd(store)
	out, err := executeCommand(root, "load", "--project", "foo", "--dry-run")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "DB=localhost") {
		t.Errorf("missing DB in output: %q", out)
	}
	if !strings.Contains(out, "PORT=5432") {
		t.Errorf("missing PORT in output: %q", out)
	}
	if !strings.Contains(out, "Generated by envy") {
		t.Errorf("missing header in output: %q", out)
	}
}

func TestLoadCmd_WritesFile(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("foo", []string{"dev"}, "dev")
	p.SetVar("dev", "DB", "localhost")
	store.Save(p)

	dir := t.TempDir()
	outFile := filepath.Join(dir, ".env")

	root := NewRootCmd(store)
	_, err := executeCommand(root, "load", "--project", "foo", "--output", outFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("reading output: %v", err)
	}
	if !strings.Contains(string(data), "DB=localhost") {
		t.Errorf("file content = %q, want DB=localhost", string(data))
	}
}

func TestLoadCmd_WithPathInheritance(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("mono", []string{"dev"}, "dev")
	p.SetVar("dev", "SHARED", "yes")
	p.SetPathVar("services/api", "dev", "PORT", "3000")
	store.Save(p)

	root := NewRootCmd(store)
	out, err := executeCommand(root, "load", "--project", "mono",
		"--path", "services/api", "--dry-run")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "PORT=3000") {
		t.Errorf("missing PORT: %q", out)
	}
	if !strings.Contains(out, "SHARED=yes") {
		t.Errorf("missing inherited SHARED: %q", out)
	}
}

func TestLoadCmd_ExportFormat(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("foo", []string{"dev"}, "dev")
	p.SetVar("dev", "DB", "localhost")
	store.Save(p)

	root := NewRootCmd(store)
	out, err := executeCommand(root, "load", "--project", "foo",
		"--dry-run", "--format", "export")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out, "export DB=localhost") {
		t.Errorf("missing export prefix: %q", out)
	}
}

func TestLoadCmd_PromptOnExistingFile(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("foo", []string{"dev"}, "dev")
	p.SetVar("dev", "DB", "localhost")
	store.Save(p)

	dir := t.TempDir()
	outFile := filepath.Join(dir, ".env")
	os.WriteFile(outFile, []byte("OLD=data"), 0o644)

	// Simulate "n" response
	root := newLoadCmd(store, strings.NewReader("n\n"))
	root.SetArgs([]string{"--project", "foo", "--output", outFile})
	var buf strings.Builder
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.Execute()

	if !strings.Contains(buf.String(), "Aborted") {
		t.Errorf("expected abort message: %q", buf.String())
	}

	data, _ := os.ReadFile(outFile)
	if string(data) != "OLD=data" {
		t.Errorf("file should be unchanged, got %q", string(data))
	}
}

func TestLoadCmd_ForceOverwrite(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("foo", []string{"dev"}, "dev")
	p.SetVar("dev", "DB", "localhost")
	store.Save(p)

	dir := t.TempDir()
	outFile := filepath.Join(dir, ".env")
	os.WriteFile(outFile, []byte("OLD=data"), 0o644)

	root := NewRootCmd(store)
	_, err := executeCommand(root, "load", "--project", "foo",
		"--output", outFile, "--force")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, _ := os.ReadFile(outFile)
	if !strings.Contains(string(data), "DB=localhost") {
		t.Errorf("file should be overwritten: %q", string(data))
	}
}

func TestLoadCmd_NonexistentProject(t *testing.T) {
	store := setupTestStore(t)
	root := NewRootCmd(store)
	_, err := executeCommand(root, "load", "--project", "nope", "--dry-run")
	if err == nil {
		t.Error("expected error for nonexistent project")
	}
}

func TestLoadCmd_NonexistentEnv(t *testing.T) {
	store := setupTestStore(t)
	p, _ := config.NewProject("foo", []string{"dev"}, "dev")
	store.Save(p)

	root := NewRootCmd(store)
	_, err := executeCommand(root, "load", "--project", "foo",
		"--env", "nope", "--dry-run")
	if err == nil {
		t.Error("expected error for nonexistent env")
	}
}
