package dotenv

import (
	"bytes"
	"strings"
	"testing"
)

func TestWrite_Sorted(t *testing.T) {
	var buf bytes.Buffer
	vars := map[string]string{"C": "3", "A": "1", "B": "2"}
	err := Write(&buf, vars, WriteOptions{Sorted: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	lines := strings.Split(strings.TrimSpace(buf.String()), "\n")
	want := []string{"A=1", "B=2", "C=3"}
	if len(lines) != len(want) {
		t.Fatalf("got %d lines, want %d: %q", len(lines), len(want), buf.String())
	}
	for i, line := range lines {
		if line != want[i] {
			t.Errorf("line %d = %q, want %q", i, line, want[i])
		}
	}
}

func TestWrite_ExportFormat(t *testing.T) {
	var buf bytes.Buffer
	vars := map[string]string{"KEY": "value"}
	err := Write(&buf, vars, WriteOptions{Format: FormatExport})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	got := strings.TrimSpace(buf.String())
	if got != `export KEY=value` {
		t.Errorf("output = %q, want %q", got, `export KEY=value`)
	}
}

func TestWrite_Header(t *testing.T) {
	var buf bytes.Buffer
	vars := map[string]string{"KEY": "value"}
	err := Write(&buf, vars, WriteOptions{
		Header: "Generated by envy",
		Sorted: true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.HasPrefix(buf.String(), "# Generated by envy\n") {
		t.Errorf("output should start with header comment: %q", buf.String())
	}
}

func TestWrite_EmptyVars(t *testing.T) {
	var buf bytes.Buffer
	err := Write(&buf, map[string]string{}, WriteOptions{Sorted: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if buf.String() != "" {
		t.Errorf("expected empty output, got %q", buf.String())
	}
}

func TestWrite_ValuesNeedingQuoting(t *testing.T) {
	tests := []struct {
		name  string
		value string
		want  string
	}{
		{"with space", "hello world", `KEY="hello world"`},
		{"with hash", "foo#bar", `KEY="foo#bar"`},
		{"with double quote", `say "hi"`, `KEY="say \"hi\""`},
		{"with newline", "line1\nline2", `KEY="line1\nline2"`},
		{"with backslash", `path\to`, `KEY="path\\to"`},
		{"empty value", "", `KEY=""`},
		{"simple value", "simple", "KEY=simple"},
		{"with dollar", "$HOME", `KEY="$HOME"`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			err := Write(&buf, map[string]string{"KEY": tt.value}, WriteOptions{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			got := strings.TrimSpace(buf.String())
			if got != tt.want {
				t.Errorf("output = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestWrite_RoundTrip(t *testing.T) {
	original := map[string]string{
		"SIMPLE":     "value",
		"WITH_SPACE": "hello world",
		"WITH_QUOTE": `say "hello"`,
		"WITH_HASH":  "foo#bar",
		"EMPTY":      "",
		"NEWLINE":    "line1\nline2",
		"BACKSLASH":  `path\to\file`,
		"URL":        "postgres://host:5432/db?opt=val",
	}

	var buf bytes.Buffer
	err := Write(&buf, original, WriteOptions{Sorted: true})
	if err != nil {
		t.Fatalf("Write: %v", err)
	}

	parsed, err := Parse(strings.NewReader(buf.String()))
	if err != nil {
		t.Fatalf("Parse: %v\nwritten:\n%s", err, buf.String())
	}

	if len(parsed) != len(original) {
		t.Fatalf("got %d vars, want %d", len(parsed), len(original))
	}
	for k, v := range original {
		if parsed[k] != v {
			t.Errorf("key %q: got %q, want %q", k, parsed[k], v)
		}
	}
}

func TestWrite_WithDisabledVars(t *testing.T) {
	var buf bytes.Buffer
	err := Write(&buf, map[string]string{"ACTIVE": "yes"}, WriteOptions{
		Sorted:       true,
		DisabledVars: map[string]string{"API_KEY": "secret", "TOKEN": "abc 123"},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	got := strings.TrimSpace(buf.String())
	if !strings.Contains(got, "ACTIVE=yes") {
		t.Fatalf("missing active var: %q", got)
	}
	if !strings.Contains(got, "# API_KEY=secret") {
		t.Fatalf("missing disabled API_KEY: %q", got)
	}
	if !strings.Contains(got, "# TOKEN=\"abc 123\"") {
		t.Fatalf("missing disabled TOKEN: %q", got)
	}

	parsed, err := ParseWithDisabled(strings.NewReader(buf.String()))
	if err != nil {
		t.Fatalf("ParseWithDisabled: %v\nwritten:\n%s", err, buf.String())
	}
	if parsed.Vars["ACTIVE"] != "yes" {
		t.Errorf("ACTIVE = %q, want %q", parsed.Vars["ACTIVE"], "yes")
	}
	if parsed.DisabledVars["API_KEY"] != "secret" {
		t.Errorf("API_KEY = %q, want %q", parsed.DisabledVars["API_KEY"], "secret")
	}
	if parsed.DisabledVars["TOKEN"] != "abc 123" {
		t.Errorf("TOKEN = %q, want %q", parsed.DisabledVars["TOKEN"], "abc 123")
	}
}
